- name: Dependent Issues
  # You may pin to the exact commit or the version.
  # uses: z0al/dependent-issues@950226e7ca8fc43dc209a7febf67c655af3bdb43
  uses: z0al/dependent-issues@v1.5.2
  with:
    # The label to use to mark dependent issues
    label: # optional, default is dependent
    # Enable checking for dependencies in issues
    check_issues: on
    # Ignore Dependabot PRs.
    ignore_dependabot: on
    # A comma-separated list of keywords
    keywords: # optional, default is depends on, blocked by
    # A custom comment body. It supports `{{ dependencies }}` token.
    comment: # optional, default is This PR/issue depends on:
    
{{ dependencies }}
By **[Dependent Issues](https://github.com/z0al/dependent-issues)** (🤖). Happy coding!
